# Generated by Django 3.2 on 2021-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_val', models.BinaryField(max_length=16)),
                ('ids_val', models.BinaryField(max_length=16)),
                ('k1_val', models.BinaryField(max_length=16)),
                ('k2_val', models.BinaryField(max_length=16)),
                ('k3_val', models.BinaryField(max_length=16)),
                ('k4_val', models.BinaryField(max_length=16)),
                ('n1_val', models.BinaryField(max_length=16)),
                ('n2_val', models.BinaryField(max_length=16)),
                ('A_val', models.BinaryField(max_length=16)),
                ('B_val', models.BinaryField(max_length=16)),
                ('C_val', models.BinaryField(max_length=16)),
                ('D_val', models.BinaryField(max_length=16)),
            ],
        ),
    ]
